### ISSUE TITLE
Ignore hidden folders when detecting charts or only package Charts with chart.yaml

### ISSUE THREAD

**Issue by ccremer** [helm/chart-releaser-action#12]
If I have a charts repository, where the chart directories are in root instead of `charts/` or `stable/` etc, and I use
```yaml
      with:
        charts_dir: .
```
then the Pipeline failes with:
```
Installing chart-releaser...
Packaging chart '.github'...
Error: chart metadata (Chart.yaml) missing
```

Obviously .github dir contains the workflow files and not any charts.

Possible solutions:
* Ignore hidden folders by default, but make it configurable to exclude additional folders (e.g. `/docs`)
* Skip folders that do not have Chart.yaml in it. If there's an (invalid) chart without this file, then people will notice anyway that something is wrong, since the chart does not get published

**Comment by bittner** [comment]
Maybe ignore and print out a warning for folders that don't have a `Chart.yaml` file?
