### ISSUE TITLE
Flag --charts-repo is deprecated

### ISSUE THREAD

**Issue by jftanner** [helm/chart-releaser-action#122]
Running the action logs `ATTENTION: Flag --charts-repo is deprecated. It does not have any effect.`

I believe the option can safely be removed, since https://github.com/helm/chart-releaser/pull/144.

I'll open a PR to do this over the weekend. In the meantime, I welcome any comments or concerns.

**Comment by viceice** [comment]
can we get a release with this fix please?

**Comment by jftanner** [comment]
I can't trigger releases, but perhaps @davidkarlsen can.
