### ISSUE TITLE
Feature request: single chart repository with chart files in repository root

### ISSUE THREAD

**Issue by maximemoreillon** [helm/chart-releaser-action#132]
Hello,

Thanks for making this GitHub Action, it has made my chart publishing workflow much more convenient!

One issue I am having with it though is that I prefer to have each of my charts in their own repo as opposed to bringing them all in a single monorepo. Currently, the chart-releaser action requires me to put my chart files in a dedicated folder but I would prefer if it was possible to have those in the root of the repository.

In this sense, this relates to #87 and #43 

Is this something that could be considered for a future version?

Best regards,

**Comment by maximemoreillon** [comment]
After studying about Helm repositories more in details, I realize that the chart releaser action is meant to be used for git repositories that manage Helm repos and not charts.
Thus, I am closing this issue. Sorry for the misunderstanding.

**Comment by MPParsley** [comment]
This is unfortunate as there is a use case for repositories that want to host their own Helm chart.
