### ISSUE TITLE
`charts_repo_url` is outdated?

### ISSUE THREAD

**Issue by Gekko0114** [helm/chart-releaser-action#142]
Hi,

Thanks for your great work on this action.

In the README.md file, `charts_repo_url` is defined. However, in the codebase, there are no variables named `charts_repo_url`.
Is the README.md outdated?

**Comment by spuxx1701** [comment]
Same issue!

**Comment by GeunjeLEE** [comment]
I am facing the same issue.
Are there any new updates to fix this issue?

**Comment by spuxx1701** [comment]
@GeunjeLEE no fix, the document is simply outdated and charts_repo_url is no longer there.

**Comment by GeunjeLEE** [comment]
@spuxx1701 

Oh cool, i appreciate you keeping me informed.

**Comment by cpanato** [comment]
fixed in #144
