### ISSUE TITLE
Add flag package-with-index

### ISSUE THREAD

**Issue by IGx89** [helm/chart-releaser-action#147]
Hello! chart-releaser v1.6 added flag `--package-with-index`: https://github.com/helm/chart-releaser/pull/304. Once #146 gets merged would you be able to add that flag to this action as well?

Thanks!

**Comment by or4dx** [comment]
Hello not sure if this has been raised before but when I use the `packages_with_index: true` values it still packages it and stores it as a release instead of with the index.yaml file in the gh-pages branch

**Comment by IGx89** [comment]
@or4dx there hasn't been a release sadly since this functionality was added to the action -- still waiting for it.

**Comment by IGx89** [comment]
@or4dx they just released v1.6 it looks! Give that a try.

**Comment by IGx89** [comment]
Closing since this is now added (thanks!), although I haven't been able to use it myself yet due to an unrelated regression (#171).
