### ISSUE TITLE
Helm 3 support

### ISSUE THREAD

**Issue by estahn** [helm/chart-releaser-action#29]
`helm/chart-testing-action@v1.0.0-rc.2` has helm 3 support and `chart-releaser-action` should be inline with it.

**Comment by scottrigby** [comment]
This is done ✅ 

See:
- https://github.com/helm/chart-releaser/pull/47
- https://github.com/helm/chart-releaser/releases/tag/v1.0.0-beta.1
- https://github.com/helm/chart-releaser-action/blob/master/cr.sh#L21
https://github.com/helm/chart-releaser-action/blob/a2cb342e3af55f5a5b247fe5dd1da3775e9010d3/cr.sh#L21

You can see this working on both chart API `v1` (Helm 2 or 3) and `v2` (Helm 3 only) charts in the Helm GH Actions Demo repo: https://github.com/helm/charts-repo-actions-demo/
