### ISSUE TITLE
Detecting changed files is broken in v1.1.0

### ISSUE THREAD

**Issue by aabouzaid** [helm/chart-releaser-action#61]
Hello,

because of the latest change in v1.1.0, now `charts_dir` doesn't work with "." (current working directory)
https://github.com/helm/chart-releaser-action/blob/c3d308d0c55d41f25565d9db5534da82dd8b07d7/cr.sh#L228

This expression cannot be less than `2` that's why no changes detected in the current working directory.

```
$ echo $(( $(tr "/" "\n" <<< "." | wc -l) + 1 )) 
2
```

The `+ 1` should be removed.

**Comment by ohdearaugustin** [comment]
I can confirm that issue.

**Comment by ravikrs** [comment]
I also faced this issue after upgrading version to 1.1.0
Downgraded the chart-releaser-action version to 1.0.0 for now

**Comment by madchap** [comment]
Still seems to be present in 1.2.0.

**Comment by monotek** [comment]
Same here: https://github.com/monotek/zammad-helm/runs/2050548488?check_suite_focus=true

**Comment by unguiculus** [comment]
Fixed in #83
