### ISSUE TITLE
CR no longer identifies chart changes when charts-dir is "." and charts live at the root level

### ISSUE THREAD

**Issue by chrisbsmith** [helm/chart-releaser-action#82]
In version 1.0.0, when `charts-dir=.` was supplied, the `cr.sh` set the `fields=1`. 

https://github.com/helm/chart-releaser-action/blob/97237943efb7a48269d47a642ec5fdff675aa55f/cr.sh#L202-L207

This allowed the [`cut -d '/'`](https://github.com/helm/chart-releaser-action/blob/97237943efb7a48269d47a642ec5fdff675aa55f/cr.sh#L209) to find changes in charts that were in a directory at the root level of the repo, something like this:

```
.
├── ci
├── data
├── edge
├── fabric
├── observables
├── secrets
├── sense
└── spire
```

as well as a second level directory like this:

```
.
├── fabric
│   ├── charts
│   ├── control
│   ├── control-api
│   ├── jwt
│   ├── jwt-gov
│   ├── redis
│   └── templates
```

In `1.2.0`, the fields are determined by the calculated depth:
https://github.com/helm/chart-releaser-action/blob/c25b74a986eb925b398320414b576227f375f946/cr.sh#L228-L231

However, when `charts_dir=.`, the calculated depth is `2`, which leads fields to be `1-2` in the following `cut` command.

As we were investigating why this was failing for us, we found that the `cut -d '/' -f 1-2` was returning `edge/Chart.yaml` rather than just `edge`. When `edge/Chart.yaml` gets passed to [`filter_charts()`](https://github.com/helm/chart-releaser-action/blob/c25b74a986eb925b398320414b576227f375f946/cr.sh#L210-L220) it get immediately dumped because it's not a directory. 

In this case, cr 1.2.0 only finds updates in our repo when it's in a chart that is in a sub folder, like `./fabric/jwt`. 

Our remediation was to roll back to 1.0.0, but we'll continue to look at this and aim to get a change submitted.

[This is our helm-charts repo](https://github.com/greymatter-io/helm-charts) where we run cr as part of the release process

**Comment by monotek** [comment]
+1
