### ISSUE TITLE
Node not ready for scheduling 

### ISSUE THREAD

**Issue by yolossn** [helm/chart-releaser-action#86]
`Run chart-testing (install)` step fails due to nodes not in the ready state. The test fails with the following logs.

```
Events:
  Type     Reason            Age               From               Message
  ----     ------            ----              ----               -------
  Warning  FailedScheduling  38s (x5 over 5m)  default-scheduler  0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
```

**Comment by SamuAlfageme** [comment]
@yolossn check out https://github.com/helm/kind-action/issues/42#issuecomment-871452772 and https://github.com/helm/kind-action/pull/43 - setting `helm/kind-action@v1.2.0` on your workflow will solve your issue.

**Comment by yolossn** [comment]
Thanks, @SamuAlfageme, that solves my issue.
